/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import Controller.Controller;
import deepspace.EnemyToUI;
import deepspace.GameState;

/**
 *
 * @author pablo
 */
public class EnemyStarShipView extends javax.swing.JPanel {
    private LootView lootView;
    private DamageView damageView;
    
    public EnemyStarShipView() {
        initComponents();
        
        lootView = new LootView();
        enemyLootPanel.add(lootView);
        
        damageView = new DamageView();
        enemyDamagePanel.add(damageView);
    }
    
    void setEnemy(EnemyToUI e){
        enemyName.setText(e.getName());
        enemyFire.setText(Float.toString(e.getAmmoPower()));
        enemyShield.setText(Float.toString(e.getShieldPower()));
        
        lootView.setLoot(e.getLoot());
        damageView.setDamage(e.getDamage());
        
        if(Controller.getInstance().getState() == GameState.BEFORECOMBAT || Controller.getInstance().getState() == GameState.INIT){
            lootView.setVisible(false);
            damageView.setVisible(false);
        }
        else{
            lootView.setVisible(true);
            damageView.setVisible(true);
        }
        
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleEnemy = new javax.swing.JLabel();
        titleFire = new javax.swing.JLabel();
        titleShield = new javax.swing.JLabel();
        enemyShield = new javax.swing.JLabel();
        enemyFire = new javax.swing.JLabel();
        enemyName = new javax.swing.JLabel();
        enemyLootPanel = new javax.swing.JPanel();
        enemyDamagePanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleEnemy.setText("Enemigo:");

        titleFire.setText("Potencia de fuego:");

        titleShield.setText("Potencia de defensa:");

        enemyShield.setText("shieldPower");

        enemyFire.setText("fire");

        enemyName.setText("enemyName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleShield)
                            .addComponent(titleFire)
                            .addComponent(titleEnemy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enemyName)
                            .addComponent(enemyFire)
                            .addComponent(enemyShield)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enemyLootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(enemyDamagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEnemy)
                    .addComponent(enemyName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleFire)
                    .addComponent(enemyFire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleShield)
                    .addComponent(enemyShield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enemyLootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enemyDamagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel enemyDamagePanel;
    private javax.swing.JLabel enemyFire;
    private javax.swing.JPanel enemyLootPanel;
    private javax.swing.JLabel enemyName;
    private javax.swing.JLabel enemyShield;
    private javax.swing.JLabel titleEnemy;
    private javax.swing.JLabel titleFire;
    private javax.swing.JLabel titleShield;
    // End of variables declaration//GEN-END:variables
}
