/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.LootToUI;

/**
 *
 * @author pablo
 */
public class LootView extends javax.swing.JPanel {

    /**
     * Creates new form LootView
     */
    public LootView() {
        initComponents();
    }
    
    void setLoot(LootToUI loot){
        weapons.setText(Integer.toString(loot.getnWeapons()));
        shields.setText(Integer.toString(loot.getnShields()));
        hangar.setText(Integer.toString(loot.getnHangars()));
        supplies.setText(Integer.toString(loot.getnSupplies()));
        medals.setText(Integer.toString(loot.getnMedals()));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        titleWeapons = new javax.swing.JLabel();
        titleShields = new javax.swing.JLabel();
        titleSupplies = new javax.swing.JLabel();
        supplies = new javax.swing.JLabel();
        shields = new javax.swing.JLabel();
        weapons = new javax.swing.JLabel();
        titleHangar = new javax.swing.JLabel();
        titleMedals = new javax.swing.JLabel();
        medals = new javax.swing.JLabel();
        hangar = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(310, 120));

        title.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        title.setText("Botín");

        titleWeapons.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        titleWeapons.setText("Armas:");

        titleShields.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        titleShields.setText("Escudos:");

        titleSupplies.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        titleSupplies.setText("Combustible:");

        supplies.setText("supplies");

        shields.setText("shields");

        weapons.setText("weapons");

        titleHangar.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        titleHangar.setText("Hangar:");

        titleMedals.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        titleMedals.setText("Medallas:");

        medals.setText("medals");

        hangar.setText("hangar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleSupplies)
                            .addComponent(titleShields)
                            .addComponent(titleWeapons))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplies)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(shields)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(titleMedals))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(weapons)
                                        .addGap(47, 47, 47)
                                        .addComponent(titleHangar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medals)
                                    .addComponent(hangar))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleWeapons)
                    .addComponent(weapons)
                    .addComponent(titleHangar)
                    .addComponent(hangar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleShields)
                    .addComponent(shields)
                    .addComponent(titleMedals)
                    .addComponent(medals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleSupplies)
                    .addComponent(supplies))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hangar;
    private javax.swing.JLabel medals;
    private javax.swing.JLabel shields;
    private javax.swing.JLabel supplies;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleHangar;
    private javax.swing.JLabel titleMedals;
    private javax.swing.JLabel titleShields;
    private javax.swing.JLabel titleSupplies;
    private javax.swing.JLabel titleWeapons;
    private javax.swing.JLabel weapons;
    // End of variables declaration//GEN-END:variables
}
