/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.WeaponToUI;

/**
 *
 * @author pablo
 */
public class WeaponView extends javax.swing.JPanel implements CombatElementView {
    private boolean selected = false;

    public WeaponView() {
        initComponents();
        setOpaque(selected);
    }

    @Override
    public boolean isSelected () {
        return selected;
    }
    
    /**
     * @brief Asocia al panel un objeto ToUI de WeaponView
     * @param weapon : Objeto WeaponToUI que se le pasará a la vista
     */
    void setWeapon(WeaponToUI weapon){
        weaponType.setText(weapon.getType().toString());
        weaponPower.setText(Float.toString(weapon.getPower()));
        weaponUses.setText(Integer.toString(weapon.getUses()));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleWeaponType = new javax.swing.JLabel();
        titleWeaponPower = new javax.swing.JLabel();
        titleWeaponUses = new javax.swing.JLabel();
        weaponPower = new javax.swing.JLabel();
        weaponType = new javax.swing.JLabel();
        weaponUses = new javax.swing.JLabel();

        setBackground(new java.awt.Color(185, 255, 156));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Arma"));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        titleWeaponType.setText("Tipo:");

        titleWeaponPower.setText("Potencia:");

        titleWeaponUses.setText("Usos:");

        weaponPower.setText("power");

        weaponType.setText("type");

        weaponUses.setText("uses");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleWeaponPower)
                    .addComponent(titleWeaponType)
                    .addComponent(titleWeaponUses))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weaponUses)
                    .addComponent(weaponType)
                    .addComponent(weaponPower))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleWeaponType)
                    .addComponent(weaponType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleWeaponPower)
                    .addComponent(weaponPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleWeaponUses)
                    .addComponent(weaponUses))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque (selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titleWeaponPower;
    private javax.swing.JLabel titleWeaponType;
    private javax.swing.JLabel titleWeaponUses;
    private javax.swing.JLabel weaponPower;
    private javax.swing.JLabel weaponType;
    private javax.swing.JLabel weaponUses;
    // End of variables declaration//GEN-END:variables
}
